- name: Wipe 
  tags: 
    - wipe-app-python
  when: web_app_full_wipe
  block: 
    - name: Stop and remove {{ container_name }}
      docker_container:
        name: "{{ container_name }}"
        state: absent
        keep_volumes: false