password: ENC[AES256_GCM,data:ezS3d3/Y9zF6UWQEJ1Qfpg==,iv:ZbaRM9VhFPdaKbSGqgAtEh3GZeJzi+HJLhyYrUhK+Bg=,tag:ZmrpPR1mgE9UUFTG+9wzHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-11T19:49:26Z"
    mac: ENC[AES256_GCM,data:JzAESLhIlYBPYMtSHS0f8SMr8N006G6zGraJjBJM7FMPcW9ptIRQXrsIsim5/63xEIChvVZ3/3SCYxxIHacz5QgGQXZtX+HI7BQdWSIR2AbAGegTlUfpIj07PfuXSLDCYui9TptWia7s1qysKdg+H4XprvZyShsBCScqE5c6IkI=,iv:wdgsEqw0Zxed3ZGBMyqRkWmCMSFG85uS/qCB+wnfGtM=,tag:uGkXc6r5J/U45DJrmSNjCA==,type:str]
    pgp:
        - created_at: "2024-04-11T19:47:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DHmJmNWko62USAQdACuHGugWxNLmg1s/WdHHOCPuXKT4O3mae9GnCbMsoyzYw
            18Py+QQ60vuIDetgDfKMqSmsLr3gU6x8qubkunInewYGbdP0CNzFTX4EicsCTcLl
            1GgBCQIQLZtjTXkhhPOrV189dRQH6DTvr33u4QOfvx59lSwPjg6RnvSW+KwcWk7P
            69Yd/4zXoyPugOZ6iKq3ctrYWQ7iZpx2an9XIuQdPhRe6341owTIKFZcbyfD0+3I
            xmjOq47EAQlBTw==
            =/lee
            -----END PGP MESSAGE-----
          fp: A76AF512CCA940E6819189B399C691794E2C7190
    unencrypted_suffix: _unencrypted
    version: 3.8.1
